name: First Workflow

on: [push]

jobs:
    first-workflow:
        runs-on: ubuntu-latest

        steps:
            - name: First Step
              run: |
                echo "Hello, World!"
                echo "First Workflow!"

            - name: Second Step
              run: |
                echo "Yaml File"
                echo ".yml"