name: Cron Job Workflow

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes


jobs:
  cron-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: CronWorkflow
        run: |
          echo "Hello Cron Job!"