name: 🚀 FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 FTP Deploy
    runs-on: ubuntu-latest
    steps:

    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📦 Install Node dependencies
      run: |
          npm install
          npm run build
    
    - name: 🧰 Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.codersujon.com
        username: dev@codersujon.com
        password: h@D(^Am=Uj#RyGAZ
        server-dir: /live.codersujon.com/

        exclude: |
            **/.git*
            **/node_modules/**
            **/vendor/**
            .github/**
